### **Tensorflow1강 Tensorflow의 자료형***
tensorflow의 자료형과 동작 방식을 배운다.

In [1]:
import tensorflow as tf

In [2]:
placeholder = tf.placeholder(dtype=tf.float32, shape=[3,3])
Variables = tf.Variable([1, 2, 3, 4, 5], dtype=tf.float32)
constant = tf.constant([10, 20, 30, 40, 50], dtype=tf.float32)

**placeholder** : 데이터를 저장시키는 공간, tensor랑 mapping시키는 역할, 그래프를 만들지 않는다.  
**Variables** : 하나의 객체, weight를 저장할 때 쓴다. 정의할 때 type을 맞춰줘야 error를 줄일 수 있다.  
**constant** : 상수, 메소드  
constant, Variables, placeholder 그래프가 다르게 그려진다.

tensorflow가 돌아갈 때, python level에 대해서는 연산을 허용하지 않는다.(현 상태에서 print(placeholder)를 하게되면 tensor의 형태가 출력된다.)  
But, 그래프를 생성하고 Session(그래프 한 덩어리)을 device에 올린다.  
Session은 파일이다! 파일 형태로 쓰고 읽는다.  

ex) 5 x 4 x 3 x 2 x 1 = ?  
![ex1_1](./image/1_1.png)

ex) 2(5 + 4) + 3(1 + 2) = ?  
![ex1_2](./image/1_2.png)

### **const**

In [3]:
const1 = tf.constant([5])
const2 = tf.constant([3])
const3 = tf.constant([2])

result_const = const1 * const2 + const3
print(result_const)

Tensor("add:0", shape=(1,), dtype=int32)


In [4]:
sess = tf.Session()
result = sess.run(result_const)
print(result)

[17]


### **Variable**
variable은 반드시 초기화가 필요한 tensor다.

In [5]:
var1 = tf.Variable([5])
var2 = tf.Variable([3])
var3 = tf.Variable([2])

result_var = var1 * var2 + var3

In [6]:
# error code
#sess = tf.Session()
#result = sess.run(result_value, feed_dict=feed_dict)
#print(result)

sess = tf.Session()
init = tf.global_variables_initializer()  #tf.initialize_all_variables() 사용시 warnning
sess.run(init)
result = sess.run(result_var)
print(result)

[17]


### **placeholder**

In [7]:
image = [[1, 2, 3, 4, 5],
         [5, 4, 3, 2, 1],
         [10, 20, 30, 40, 50]]
label = [10, 20, 30 ,40 ,50]

ph_image = tf.placeholder( dtype=tf.float32 )
ph_label = tf.placeholder( dtype=tf.float32 )

result_tensor = ph_image + ph_label

feed_dict = {ph_image:image, ph_label:label}  # tensor랑 mapping시키는 부분. Session() 전에만 해주면 된다.

In [8]:
sess = tf.Session()  # sessiond이 열림
result = sess.run(result_tensor, feed_dict=feed_dict)  # 그래프가 만들어진다
print(result)

[[ 11.  22.  33.  44.  55.]
 [ 15.  24.  33.  42.  51.]
 [ 20.  40.  60.  80. 100.]]
